### ISSUE TITLE
Data preprocessing code for KITTI?

### ISSUE THREAD

**Issue by davezdeng8** [zgojcic/Rigid3DSceneFlow#13]
Will you release your data preprocessing code for stereo kitti and lidar kitti?
Thank you.

**Comment by zgojcic** [comment]
Hi, 

we have published all the preprocessing scripts in `data_preprocessing` folder.

Let me know if you need any other help.
Best
Zan

**Comment by davezdeng8** [comment]
Thank you for the quick response. If I'm understanding the code correctly, it seems the data_preprocessing folder contains code to generate the stereo kitti dataset but not the lidar kitti dataset. Will you release the code for lidar kitti as well? Thank you.

**Comment by zgojcic** [comment]
Hi, for that, we have used the processing scripts from [MeteorNet](https://github.com/xingyul/meteornet/tree/master/scene_flow_kitti). If I remember, the only difference was that we adapted the coordinate system to fit ours. Is there any specific reason why you would like to reprocess the lidar kitti data?

**Comment by davezdeng8** [comment]
Ah I see. I wanted to try using the entire point cloud instead of just the cropped points in front of the cameras.

**Comment by zgojcic** [comment]
I see, in that case, please use the code that I have linked above. I hope that this works out, otherwise feel free to open a new issue. 

Best
Zan
