### ISSUE TITLE
Pretrained model was expired

### ISSUE THREAD

**Issue by weihao1115** [zgojcic/Rigid3DSceneFlow#17]
Hi! Thank you for your wonderful work. I tried downloading the checkpoint by the script you provided. However, it seems the link saving the models expired, and I cannot find the pre-trained models. Could you please tell me how I can get them? 

Thank you very much for your kind help!

**Comment by weihao1115** [comment]
Besides, it seems the link saving preprocessed data expired too. Could you please also tell me how I can get the data? Thank you again for your patience and help!

**Comment by zgojcic** [comment]
Hi Weihao111,

thanks for reaching out, the links indeed don't seem to work anymore. The data/models were stored on a server that is managed by the university where I did my PhD, I contacted them already and will try to sort this out ASAP. 

I will keep you posted.

Zan

**Comment by weihao1115** [comment]
Totally understood. Thank you for your immediate reply and help.

**Comment by weihao1115** [comment]
Hi Zan,

I found the expired websites have been recovered now. 

Thank you very much for your soon response. It's awesome.

Weihao
