### ISSUE TITLE
Question about computing Rotation matrix

### ISSUE THREAD

**Issue by hi-zhengcheng** [zgojcic/Rigid3DSceneFlow#6]
Hi, thanks for the nice work. 

When computing the rotation matrix after SVD, the following line transposes both `V` and `U`:
https://github.com/zgojcic/Rigid3DSceneFlow/blob/7fa57e3ddccf605dca63ded04825bba2272cae4a/lib/utils.py#L335
But I think only `U` should be transposed here. Is this an error?

I find another implementation in the source code: 
https://github.com/zgojcic/Rigid3DSceneFlow/blob/7fa57e3ddccf605dca63ded04825bba2272cae4a/lib/model/minkowski/MinkowskiFlow.py#L344
Here only `U` is transposed.

**Comment by zgojcic** [comment]
Hi @hi-zhengcheng,

it should indeed be only `u^t`, but as this is only the computation of the determinant it actually does not matter as `det(a) = det(v^t)` and `det(vu) = det(v) * det(u)`

The rotation matrix is computed here:
https://github.com/zgojcic/Rigid3DSceneFlow/blob/7fa57e3ddccf605dca63ded04825bba2272cae4a/lib/utils.py#L339

and here only U is transposed. 

I hope this makes sense. 

Best 
Zan

**Comment by hi-zhengcheng** [comment]
Solved my question, thanks for your answer.
